const cities = [
  { id: 1, name: "Cairo" },
  { id: 2, name: "Alexandria" },
  { id: 3, name: "Giza" },
  { id: 4, name: "Shubra El-Kheima" },
  { id: 5, name: "Port Said" },
  { id: 6, name: "Suez" },
  { id: 7, name: "Luxor" },
  { id: 8, name: "Al-Mansura" },
  { id: 9, name: "El-Mahalla El-Kubra" },
  { id: 10, name: "Tanta" },
  { id: 11, name: "Asyut" },
  { id: 12, name: "Ismailia" },
  { id: 13, name: "Fayyum" },
  { id: 14, name: "Zagazig" },
  { id: 15, name: "Aswan" },
  { id: 16, name: "Damietta" },
  { id: 17, name: "Damanhur" },
  { id: 18, name: "El-Minya" },
  { id: 19, name: "Beni Suef" },
  { id: 20, name: "Sohag" },
  { id: 21, name: "Hurghada" },
  { id: 22, name: "Banha" },
  { id: 23, name: "Kafr El Sheikh" },
  { id: 24, name: "Arish" },
  { id: 25, name: "Mallawi" },
  { id: 26, name: "10th of Ramadan City" },
  { id: 27, name: "Qena" },
  { id: 28, name: "Safaga" },
  { id: 29, name: "New Nubariya" },
  { id: 30, name: "Rafah" },
];

export default cities;
